# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build"
  lane :build do
    gradle(task: "clean assembleRelease")
  end

  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :beta do
    build

    firebase_app_distribution(
        app: "1:273313984344:android:13950ca8b57a214e897f2d",
        groups: "group1",
        release_notes: "Lots of amazing new features to test out!"
    )
  end

  desc "Submit a new Beta Build to Appcenter App Distribution"
    lane :upload_appcenter do
      build

     appcenter_upload(
         api_token: "9c7ae0fcba7d73da2b7fc1649705e560b27b0f72",
         owner_name: "erimkorkmaz-gmail.com",
         owner_type: "user", # Default is user - set to organization for appcenter organizations
         app_name: "QuizApp",
         file: "app/build/outputs/apk/release/app-release-unsigned.apk",
         notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
  )
    end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

end
